apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payments
resources:
  - peerauthentication-payments-strict.yaml
  - authorizationpolicy-deny-all.yaml
  - authorizationpolicy-ledger-api-allow-gateway.yaml
  - deployment-ledger-api-canary.yaml
  - gateway-ledger-api.yaml
  - destinationrule-ledger-api.yaml
  - virtualservice-ledger-api.yaml
