---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgC4ktO3ygVDSL5PBizmklX0z4UtRnMUMqfNKkzOBrYXURUk1wUWmVvWDguzMdJC1wFG/RGtlXNORjzRROfxpAHbSfAMkkrtpSesaPcS+q52GC/rN/j9r1FnCLrARhkW8H7E5t5d+DOKGjtZpUvjokopNhYZDP/Q8O7AmxtWUArrkORJHVMs1oH0Hm36HOwABrgPoy8EzN5WyeMRPKsFshbJc2huqG9/EwZRmrx/uM31WmPGH7lMlUr5gHERFi9/11wXM29gAQ2fdAdLwDpvX5oKJhoTrOhYMd0YTPpm2Q7fKKFCwdPuxRJ9lzFQXG8FZHsoizQa6tZ2k7RqGU6ojxy9F4qPRao81WR4q2XHOwNJZrudGZhuudBTf5BjQW6MvZeSg7tSitzH5yGG8GG8ofUhiAUj26idJtelDNVqOnMqDm+bOss0zy4CX2RlNdkyCxzS2a+uC1actdl9MZ/xyXOKWKlJBLJhf12TaofJBNZhMt0ccx22dva2Zj76T3GcGOH+n+yMiHoy5JIB5gGDFiS9bK6Umw9moTtNUTnn3n5+osaM02ZPax/4ytErPVb1iHOvIpsKVfyr5GzWZwbdVdw+ExdRa8CTDzdiPST0EtiO4SlnmrF8eB+JMCdFJVj5Z0MaNSpQHEnkTKUlmvgsTyxShm1IMq4+lvfgT9T2cQ/XJJiWSRsCh7M7yrGfRXZr4nB7XNO1wh6WDSy9FzPJAIpMQGDP7soOLO0=
    STRIPE_API_KEY: AgAPBPY25Vk72/eqo2MKoAB0mHIdSIxfxmBAyQhVgMh2CUtfXXX87b8pTJ/Zvw4K9QrIfont8iFsavspsqbU/Wjm3pldhkc2OE3u+dDAjhnq8xY5FipIcHc67Z5oQkLWBT6IYybx+KTDMvI8pw+IxTH8vOaIuLLq17QAa0IhQeAtEjVErzOKPGs21DGEoQx/xQnBz74UcXGxJ4efIFP4N/YKZQaVGfX+UsU+ZXXw6XJo7GXRGEqlnXDAIQXI2AP30DFHHKFPOOSsZYGO6UNaGCcS/Uq5TqekEb9yiOlk68oDgz7hzRwotIkRq601MrnQt4mnKF6SOgzf1wZ0p78KgT5YupujUDsaSjdN2+IRukj95dgKKvEbBNjGOcnc94jPuqeX5oIGXTI07XHowkxunkt/HY8LyZ4VCsZbrXk4tGruSkfeZQSZyooHHjLiB7uL3wtf+NKlUMZ25VchP6FvH5FL6VKpMkRho6WysO5ak2+LFLjmeO1Tl/cD4O4zVJy8T6ZateEHXs9ZyjHCWEhvPThif7q9mRGA0+Uy2+2/43JKEPWcufUNHBg5hBIvVaK+JOUCWE1o84WVH9HgSYHpIZbpgm7E+bD4r46eFViXbOw6zehFg8HmStpMvhm+dxb1mI/RMsJHlAlEBr5VhmrFaU32JBWOmTsGd0zxuJrX8bf+x2QOwpX27gjd/oNTtstsnVkC9LxIetrlTxnBojOc8w0iqyrxVcpaoDAz7W2RNdoOHtuDoA==
  template:
    metadata:
      name: ledger-api-secrets
      namespace: payments
