apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: payments
resources:
  - namespace.yaml
  - serviceaccount-ledger-api.yaml
  - serviceaccount-reporting.yaml
  - rbac-reporting.yaml
  - configmap-ledger-api.yaml
  - sealedsecret-ledger-api.yaml
  - deployment-ledger-api.yaml
  - deployment-reporting.yaml
  - service-ledger-api.yaml
  - ingress.yaml
  - networkpolicy-default-deny.yaml
  - networkpolicy-ledger-api.yaml
  - networkpolicy-reporting.yaml
